spring:
  profiles:
    active: dev # \uD65C\uC131 \uD504\uB85C\uD30C\uC77C\uC744 "dev"\uB85C \uC124\uC815
    include: secret # secret \uD504\uB85C\uD30C\uC77C\uC744 \uD3EC\uD568
  servlet:
    multipart:
      max-file-size: 50MB # \uD30C\uC77C \uC5C5\uB85C\uB4DC \uC2DC \uD5C8\uC6A9\uB418\uB294 \uCD5C\uB300 \uD30C\uC77C \uD06C\uAE30
      max-request-size: 50MB # \uC694\uCCAD\uC5D0 \uD3EC\uD568\uB41C \uC804\uCCB4 \uBA40\uD2F0\uD30C\uD2B8 \uC694\uCCAD\uC758 \uCD5C\uB300 \uD06C\uAE30
  threads:
    virtual:
      enabled: true # \uAC00\uC0C1 \uC2A4\uB808\uB4DC \uD480\uC744 \uC0AC\uC6A9\uD558\uB3C4\uB85D \uC124\uC815
  datasource: # \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC5F0\uACB0 \uC815\uBCF4\uB97C \uC124\uC815, H2 \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uC0AC\uC6A9\uD558\uBA70, URL, \uC0AC\uC6A9\uC790 \uC774\uB984, \uBE44\uBC00\uBC88\uD638 \uBC0F \uB4DC\uB77C\uC774\uBC84 \uD074\uB798\uC2A4\uB97C \uC9C0\uC815
    url: jdbc:h2:./medium_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update # \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC2E4\uD589 \uC2DC \uAE30\uC874 \uD14C\uC774\uBE14\uC774\uB098 \uC2A4\uD0A4\uB9C8\uAC00 \uBCC0\uACBD\uB418\uBA74 \uC790\uB3D9\uC73C\uB85C \uC5C5\uB370\uC774\uD2B8
    properties: # Hibernate\uC758 \uB2E4\uC591\uD55C \uC18D\uC131\uC744 \uC124\uC815
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging: # \uB85C\uAE45 \uB808\uBCA8\uC744 \uC124\uC815
  level: # \uD2B9\uC815 \uD328\uD0A4\uC9C0 \uB610\uB294 \uD074\uB798\uC2A4\uC5D0 \uB300\uD55C \uB85C\uADF8 \uB808\uBCA8\uC744 \uC9C0\uC815, SQL \uCFFC\uB9AC\uC640 \uAD00\uB828\uB41C Hibernate \uBC0F Spring Transaction \uB85C\uADF8 \uB808\uBCA8\uC744 \uC870\uC815
    com.ll.medium: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: mediumLecture # \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC0AC\uC774\uD2B8\uC758 \uC774\uB984\uC744 "mediumLecture"\uC73C\uB85C \uC124\uC815
    baseUrl: "http://localhost:${server.port}" # \uC560\uD50C\uB9AC\uCF00\uC774\uC158\uC758 \uAE30\uBCF8 URL\uC744 \uC124\uC815
  tempDirPath: c:/temp/medium_dev/temp # \uC784\uC2DC \uB514\uB809\uD1A0\uB9AC \uACBD\uB85C\uB97C \uC124\uC815
  genFile:
    dirPath: c:/temp/medium_dev # \uC0DD\uC131\uB41C \uD30C\uC77C\uC774 \uC800\uC7A5\uB420 \uB514\uB809\uD1A0\uB9AC \uACBD\uB85C\uB97C \uC124\uC815